#!/bin/sh
set -e

if ! command -v gh >/dev/null 2>&1; then
  echo "gh not found; install GitHub CLI first." >&2
  exit 1
fi

: "${ACR_USERNAME:?Missing ACR_USERNAME}"
: "${ACR_PASSWORD:?Missing ACR_PASSWORD}"
: "${AZURE_OPENAI_ENDPOINT:?Missing AZURE_OPENAI_ENDPOINT}"
: "${AZURE_OPENAI_DEPLOYMENT:?Missing AZURE_OPENAI_DEPLOYMENT}"
: "${AZURE_OPENAI_API_VERSION:?Missing AZURE_OPENAI_API_VERSION}"
: "${AZURE_OPENAI_API_KEY:?Missing AZURE_OPENAI_API_KEY}"
: "${TELEGRAM_BOT_TOKEN_DEFAULT:?Missing TELEGRAM_BOT_TOKEN_DEFAULT}"
: "${OPENCLAW_GATEWAY_TOKEN:?Missing OPENCLAW_GATEWAY_TOKEN}"
: "${OPENCLAW_STORAGE_ACCOUNT:?Missing OPENCLAW_STORAGE_ACCOUNT}"
: "${OPENCLAW_STORAGE_KEY:?Missing OPENCLAW_STORAGE_KEY}"
: "${OPENCLAW_FILE_SHARE:?Missing OPENCLAW_FILE_SHARE}"

# Optional
TELEGRAM_BOT_TOKEN_MO2DRKBOT=${TELEGRAM_BOT_TOKEN_MO2DRKBOT:-}

set_secret() {
  name="$1"
  value="$2"
  printf "%s" "$value" | gh secret set "$name" --repo Wrk-Flo/openclaw-prod
}

set_secret ACR_USERNAME "$ACR_USERNAME"
set_secret ACR_PASSWORD "$ACR_PASSWORD"
set_secret AZURE_OPENAI_ENDPOINT "$AZURE_OPENAI_ENDPOINT"
set_secret AZURE_OPENAI_DEPLOYMENT "$AZURE_OPENAI_DEPLOYMENT"
set_secret AZURE_OPENAI_API_VERSION "$AZURE_OPENAI_API_VERSION"
set_secret AZURE_OPENAI_API_KEY "$AZURE_OPENAI_API_KEY"
set_secret TELEGRAM_BOT_TOKEN_DEFAULT "$TELEGRAM_BOT_TOKEN_DEFAULT"
set_secret OPENCLAW_GATEWAY_TOKEN "$OPENCLAW_GATEWAY_TOKEN"
set_secret OPENCLAW_STORAGE_ACCOUNT "$OPENCLAW_STORAGE_ACCOUNT"
set_secret OPENCLAW_STORAGE_KEY "$OPENCLAW_STORAGE_KEY"
set_secret OPENCLAW_FILE_SHARE "$OPENCLAW_FILE_SHARE"

if [ -n "$TELEGRAM_BOT_TOKEN_MO2DRKBOT" ]; then
  set_secret TELEGRAM_BOT_TOKEN_MO2DRKBOT "$TELEGRAM_BOT_TOKEN_MO2DRKBOT"
fi

echo "Secrets updated for Wrk-Flo/openclaw-prod."
