#!/bin/sh
set -e

if ! command -v gh >/dev/null 2>&1; then
  echo "gh not found; install GitHub CLI first." >&2
  exit 1
fi

: "${ACR_USERNAME:?Missing ACR_USERNAME}"
: "${ACR_PASSWORD:?Missing ACR_PASSWORD}"
: "${AZURE_OPENAI_ENDPOINT:?Missing AZURE_OPENAI_ENDPOINT}"
: "${AZURE_OPENAI_DEPLOYMENT:?Missing AZURE_OPENAI_DEPLOYMENT}"
: "${AZURE_OPENAI_API_VERSION:?Missing AZURE_OPENAI_API_VERSION}"
: "${AZURE_OPENAI_API_KEY:?Missing AZURE_OPENAI_API_KEY}"
: "${TELEGRAM_BOT_TOKEN_DEFAULT:?Missing TELEGRAM_BOT_TOKEN_DEFAULT}"
: "${OPENCLAW_GATEWAY_TOKEN:?Missing OPENCLAW_GATEWAY_TOKEN}"

# Optional (webhook mode)
TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL:-}
TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET:-}

if [ -n "$TELEGRAM_WEBHOOK_URL" ] && [ -z "$TELEGRAM_WEBHOOK_SECRET" ]; then
  echo "TELEGRAM_WEBHOOK_URL set but TELEGRAM_WEBHOOK_SECRET is missing" >&2
  exit 1
fi

# Optional (secondary bot)
TELEGRAM_BOT_TOKEN_MO2DRKBOT=${TELEGRAM_BOT_TOKEN_MO2DRKBOT:-}
# Optional (skill runtimes)
GH_TOKEN=${GH_TOKEN:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}

set_secret() {
  name="$1"
  value="$2"
  printf "%s" "$value" | gh secret set "$name" --repo Wrk-Flo/openclaw-prod
}

set_secret ACR_USERNAME "$ACR_USERNAME"
set_secret ACR_PASSWORD "$ACR_PASSWORD"
set_secret AZURE_OPENAI_ENDPOINT "$AZURE_OPENAI_ENDPOINT"
set_secret AZURE_OPENAI_DEPLOYMENT "$AZURE_OPENAI_DEPLOYMENT"
set_secret AZURE_OPENAI_API_VERSION "$AZURE_OPENAI_API_VERSION"
set_secret AZURE_OPENAI_API_KEY "$AZURE_OPENAI_API_KEY"
set_secret TELEGRAM_BOT_TOKEN_DEFAULT "$TELEGRAM_BOT_TOKEN_DEFAULT"
if [ -n "$TELEGRAM_WEBHOOK_URL" ]; then
  set_secret TELEGRAM_WEBHOOK_URL "$TELEGRAM_WEBHOOK_URL"
  set_secret TELEGRAM_WEBHOOK_SECRET "$TELEGRAM_WEBHOOK_SECRET"
fi
set_secret OPENCLAW_GATEWAY_TOKEN "$OPENCLAW_GATEWAY_TOKEN"

if [ -n "$TELEGRAM_BOT_TOKEN_MO2DRKBOT" ]; then
  set_secret TELEGRAM_BOT_TOKEN_MO2DRKBOT "$TELEGRAM_BOT_TOKEN_MO2DRKBOT"
fi
if [ -n "$GH_TOKEN" ]; then
  set_secret GH_TOKEN "$GH_TOKEN"
fi
if [ -n "$OPENAI_API_KEY" ]; then
  set_secret OPENAI_API_KEY "$OPENAI_API_KEY"
fi

echo "Secrets updated for Wrk-Flo/openclaw-prod."
